
services:
  zero-green:
    image: techblog/zerobyte-whatsapp-notification-proxy
    container_name: zero-green
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - ID_INSTANCE=
      - TOKEN=
